#!/usr/bin/env ruby

require 'load_tracer'
require 'optparse'

options = { format: :json }

opt_parse = OptionParser.new do |opt|
  opt.banner = 'Usage: rutrace programfile'
  opt.on('-f', '-f format', 'specify output format.') { |format| options[:format] = format.to_sym }

  opt.parse!(ARGV)
end

if ARGV.first.nil?
  puts opt_parse
else
  path = File.expand_path(ARGV.first, Dir.pwd)

  puts LoadTracer.trace(format: options[:format], exclude_files: ['rutrace']) { require_relative path }
end
